# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(default='N/A', max_length=100)),
                ('asset_room', models.CharField(max_length=80)),
                ('asset_pv', models.IntegerField(default='N/A')),
            ],
            options={
                'db_table': 'asset_table_1',
            },
        ),
    ]
