# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email_id',
            new_name='asset_room',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='users',
            name='asset_pv',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
